#!/bin/sh

#  setenv.sh
#  async_wake_ios
#
#  Created by Etienne Stalmans on 20/12/2017.
#  Copyright © 2017 Ian Beer. All rights reserved.

export PATH=$PATH:/staaldraad/usr/local/bin:/staaldraad/bin:/staaldraad/sbin:/staaldraad/usr/bin
